spring:
  security:
    user:
      name: admin
      password: 321
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/management_db
    username: postgres
    password: berkorion
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8090


